stages:
  - build docker image

build docker image:
  stage: build docker image
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  environment: production
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - deploy
  only:
    - main
